### ISSUE TITLE
ERROR:cutplace:field type part must be a single word, but after 'Integer' there also is ''

### ISSUE THREAD

**Issue by JonathanXC** [roskakori/cutplace#121] opened 2019-05-23 00:21 UTC
<img width="491" alt="2019-05-22 19_20_27-cid_customers_with_types_and_rules - Excel" src="https://user-images.githubusercontent.com/50933045/58217073-c01cea00-7cc6-11e9-93d3-7c3e801cdffc.png">

Running cutplace 0.8.8, I'm trying to undertake basic validation of a CSV file.
When a run cutplace cid_customers_with_types_and_rules.ods customers.csv
I see next: ERROR:cutplace:cid_clientes.ods (R12C5): field type part must be a single word, but after 'Integer' there also is ''

For validations Example | Empty | Length all is correct
I don't understand because I download file cid_customers_with_types_and_rules.ods file from the page

**Comment by damiendurant** [comment] 2019-09-25 07:35
Hi, 

I have also different behaviour with python 2.7 on linux and windows.
It seems it's linked to the tokenize lib. I have PR a quick fix.

**Comment by sepira** [comment] 2019-10-09 07:47
I am still having this issue. Anybody know a fix on this?

**Comment by damiendurant** [comment] 2019-10-09 08:00
The PR I've made is a quick and dirty fix. I use it sometime on my CI/CD with no issue yet.

**Comment by kevalkothari** [comment] 2020-05-24 05:52
![image](https://user-images.githubusercontent.com/1439447/82746740-c4d01e80-9db0-11ea-9664-f580eeac98b0.png)

I have similar error - Any solution for it?

**Comment by preetimandole9** [comment] 2021-01-11 12:03
Facing same error in python 3.7 .
Anyone has got any solution to fix this issue

**Comment by vikaschoudhary89** [comment] 2021-12-24 05:56
This is not working guys and still getting the same issue, would there be any fix for this or this is an orphan library.

also csv file coverts to lowercase so making D as 'd' and F as 'f' and creating the issue.

please let me know

**Comment by roskakori** [comment] 2021-12-24 17:31
Hm, looks like this is related to the ODS reader which AFAIR in its core is a fairly simple XML parser. So maybe LibreOffice changed something that introduces spurious empty strings to it.

Does this still happen if you save the CID as Excel?

**Comment by roskakori** [comment] 2021-12-25 05:21
This error apparently is caused by a change in the Python tokenizer which at some point started adding a newline token even if you feed it a line with a single word and without a newline.

This is easy enough to fix but boy, the messy build processes and tools for Python projects changed since 2015... 🤮

**Closed** 2021-12-25 06:03 UTC
Labels: bug

**Comment by roskakori** [comment] 2021-12-25 06:04
It's fixed in the repo but there won't be a release until I rework the build process.

**Comment by vikaschoudhary89** [comment] 2021-12-25 21:31
Thanks @roskakori 
Yes, I tried in excel and csv and I was getting that error "found d' , 'f' but expected 'D' or 'F' even though I am providing in capital.

Any idea when this will be released?, Thanks again for your help

**Comment by roskakori** [comment] 2021-12-27 06:42
> Any idea when this will be released?, Thanks again for your help

As of now it's available from PyPI: <https://pypi.org/project/cutplace/>.
